apiVersion: apps/v1
kind: Deployment
metadata:
  name: xchalle-playground-deployement
  labels:
    app: xchalle-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xchalle-playground
  template:
    metadata:
      labels:
        app: xchalle-playground
    spec:
      containers:
      - name : xchalle-playground
        image: wil42/playground:v1
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: xchalle-playground-service
spec:
  type: NodePort
  selector:
    app: xchalle-playground
  ports:
  - name: http
    protocol: TCP
    port: 8888
    targetPort: 8888
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: xchalle-playground-ingress
spec: 
  rules:
  -http:
    paths:
    - path: /
      pathType: Prefix
      backend:
        service:
          name: xchalle-playground-service
          port:
            number: 8888
