apiVersion: v1
kind: Service
metadata:
  name: xchalle-playground-service
spec:
  type: NodePort
  selector:
    app: xchalle-playground
  ports:
  - name: http
    protocol: TCP
    port: 8888
    targetPort: 8888
