apiVersion: v1
kind: Service
metadata:
  name: xchalle-playground-service
  namespace: dev
spec:
  selector:
    app: xchalle-playground
  ports:
  - name: http
    protocol: TCP
    port: 8888
    targetPort: 8888
